# Generated by Django 5.1.8 on 2025-12-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userss", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("user", "User"),
                    ("demo_user", "Demo User"),
                ],
                default="demo_user",
                help_text="Role of the user (admin, user, demo_user)",
                max_length=20,
            ),
        ),
    ]
