# Generated by Django 5.1.8 on 2025-12-05 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userss", "0002_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_ip",
            field=models.GenericIPAddressField(
                blank=True, help_text="Last known user IP address", null=True
            ),
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this token is currently usable.",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP when token was last used", null=True
                    ),
                ),
                (
                    "rate_limit_count",
                    models.IntegerField(
                        default=0,
                        help_text="Usage counter for this token since last window",
                    ),
                ),
                ("last_rate_limit_reset", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
