# Generated by Django 5.1.8 on 2025-12-05 22:16

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userss", "0003_customuser_last_ip_apitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apitoken",
            name="key",
            field=fernet_fields.fields.EncryptedTextField(max_length=128),
        ),
    ]
