# Generated by Django 5.1.8 on 2025-12-05 10:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.CharField(max_length=1024)),
                ("image_hash", models.CharField(db_index=True, max_length=128)),
                ("raw_text", models.TextField(blank=True, null=True)),
                ("processed_text", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="uploaded",
                        help_text="Status of the image upload and processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["id"], name="core_upload_id_58d67e_idx"),
                    models.Index(
                        fields=["image_hash"], name="core_upload_image_h_2a9111_idx"
                    ),
                ],
            },
        ),
    ]
