# Generated by Django 5.1.8 on 2025-12-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_upload_auto_language_detection_upload_language_hint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="followup_qa",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of follow-up Q&A in Ollama/chat format: [{role, content, ...}, ...]",
                null=True,
            ),
        ),
    ]
