# Generated by Django 5.1.8 on 2025-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_upload_followup_qa"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Soft-delete flag for the upload.",
            ),
        ),
    ]
